services:
  downloader:
    image: arthytech/igdownloader:latest
    ports:
      - "5000:5000"
    volumes:
      - gallery_data:/app/gallery-dl
      - cookies_data:/app/cookies
    environment:
      - FLASK_ENV=production
    restart: always

volumes:
  gallery_data:
    driver: local
  cookies_data:
    driver: local
